### ISSUE TITLE
Missing style for "Missing" comments

### ISSUE THREAD

**Issue by VBWebprofi** [EWSoftware/SHFB#415]
Hello,

in the branding.css should included a "p.missing" style based on what currently rendered out with a paragraph and "style" attribut. In that case a ``<p class="missing"/>`` is available for reuse in documentation.

```css
p.missing
{
	color: #dc143c;
	font-size: 8.5pt;
	font-weight: bold;
}
```

Regards

Holger
